import type { Metadata } from "next";
import { geistSans, geistMono } from "./fonts";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import { NotesProvider } from "./components/NotesContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-dvh flex flex-col">
        <NotesProvider>
          <Header />
          <div className="flex flex-1 flex-row">
            <Sidebar />
            <div className="flex flex-1 flex-col">{children}</div>
          </div>
        </NotesProvider>
      </body>
    </html>
  );
}
