import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Cantarell } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cantarell = Cantarell({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html
    lang="en"
    className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
  >
    <body className="min-h-full flex flex-col">
      <header className="flex items-center px-4 py-4">
        <h1 className={`${cantarell.className} text-4xl sm:text-5xl md:text-6xl font-semibold text-foreground hover:text-amber-400 transition-colors duration-200 cursor-pointer`}>
  StickyDo
</h1>
      </header>
      {children}
    </body>
  </html>
);
}
